name: forcetictactoe
description: A sample web application
dependencies:
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
  uuid: '0.2.1'
  force: 
    git: git://github.com/jorishermans/dart-force.git 
  